version: '3'

services:
  authdb:
    container_name: authdbimage
    image: "postgres"
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      # Init db cluster and user password of superuser
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped

  app:
    build: .
    image: auth_service
    container_name: auth_service
    ports:
      - "8082:8082"
    depends_on:
      - authdb
    # user pass defined of respective postgres image
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://authdb:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  db-data:

