apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: appprofile
  name: appprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appprofile
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      labels:
        io.kompose.network/network: "true"
        io.kompose.service: appprofile
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://profiledb:5432/profile_db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
          image: ffiodicedev/air_profile
          name: profile-service
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
