apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: appflight
  name: appflight
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appflight
  template:
    metadata:
      labels:
        io.kompose.service: appflight
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://flightdb:5432/flight_db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
          image: ffiodicedev/air_flights
          name: flight-service
          ports:
            - containerPort: 8083
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: appflight
  name: appflight
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: appflight
