apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: appres
  name: appres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appres
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: appres
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://resdb:5432/res_db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
          image: ffiodicedev/air_res
          name: reservation-service
          ports:
            - containerPort: 8084
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: appres
  name: appres
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    io.kompose.service: appres
  type: ClusterIP
