apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db-datares
  name: db-datares
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
