apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: profiledb
  name: profiledb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: profiledb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: profiledb
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: profile_db
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: admin
            - name: restart
              value: unless-stopped
          image: postgres
          name: profdbimage
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/datapf
              name: db-datapf
      restartPolicy: Always
      volumes:
        - name: db-datapf
          persistentVolumeClaim:
            claimName: db-datapf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db-datapf
  name: db-datapf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: profiledb
  name: profiledb
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: profiledb
  type: ClusterIP