apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: resdb
  name: resdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: resdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: resdb
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: res_db
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: admin
            - name: restart
              value: unless-stopped
          image: postgres
          name: resdbimage
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/datares
              name: db-datares
      restartPolicy: Always
      volumes:
        - name: db-datares
          persistentVolumeClaim:
            claimName: db-datares
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db-datares
  name: db-datares
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: resdb
  name: resdb
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: resdb

